name: Semgrep Full Scan

on:
  workflow_dispatch:
    branches:
      - main
  schedule:
    - cron:  '0 1 * * 6'

jobs:

  semgrep-full:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        # step 2
        - name: full scan
          run: |
            semgrep \
              --sarif --output report.sarif \
              --metrics=off \
              --config="p/default"

        # step 3
        
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v3
          with:
            name: report.sarif
            path: report.sarif
            
        # step 4
        - name: Download report
          uses: actions/download-artifact@v2
          with: 
            name: report.sarif

#name: cicd-python

#on:
#  push:
#    branches:
#      - main

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v4
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
#          
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#        name: Tailscale
#        uses: tailscale/github-action@v2
#        with:
#          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
#          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
#          tags: tag:cicd-python
